### ISSUE TITLE
hex validation

### ISSUE THREAD

**Issue by approaching236** [rayalex/hexgrid#2]
there are values that are currently legal hexes that aren't really legal hexes in the cube coordinate system. For example: `Hex.new(1, 1, 1)` should actually fail, as 1 + 1 + 1 doesn't equal zero. I found this little bit on the same resource that you seem to be going off of here: http://www.redblobgames.com/grids/hexagons/#coordinates (under Cube coordinates)

**Comment by rayalex** [comment]
Resolved in #4
